# Generated by Django 3.2.3 on 2021-08-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=200)),
                ('company_email', models.EmailField(default='', max_length=200)),
                ('company_cno', models.PositiveIntegerField(default=0)),
                ('company_add', models.TextField(default='')),
                ('join_date', models.DateField(auto_now=True, null=True)),
                ('profile', models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='comp_profile/')),
                ('company_pass', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
