# Generated by Django 3.2.3 on 2021-09-05 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_companycustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(default='', max_length=200)),
                ('pro_price', models.PositiveIntegerField(default=0)),
                ('pro_qty', models.PositiveIntegerField(default=0)),
                ('pro_img', models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='product_img/')),
                ('comp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
